# Generated by Django 5.1.7 on 2025-03-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='storage_quota',
            field=models.BigIntegerField(default=1073741824),
        ),
    ]
