# Generated by Django 5.1.7 on 2025-04-02 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0002_fileupload_is_public'),
        ('file_manager', '0002_userprofile_storage_quota'),
    ]

    operations = [
    ]
